- engine/config.go
See https://github.com/TIBCOSoftware/flogo-lib/commit/e06ea66fe8367f19f033fff512dda7b14f628ba7 for details
> Fix property resolvers environment variable name

- data/mapper/expr.go
> fix for issue #22

- data/expression/script/expr_test.go
- data/expression/script/gocc/fs.bnf
- data/expression/script/gocc/lexer/acttab.go
- data/expression/script/gocc/lexer/lexer.go
- data/expression/script/gocc/lexer/transitiontable.go
- data/expression/script/gocc/parser/productionstable.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Cannot use resolver item selector without quotes
> fix bnf to support ref selector without quotes

- data/expression/script/expr_test.go
- data/expression/script/funcexpr_test.go
- data/expression/script/gocc/ast/expr.go
- data/expression/script/gocc/fs.bnf
- data/expression/script/gocc/parser/actiontable.go
- data/expression/script/gocc/parser/gototable.go
- data/expression/script/gocc/parser/parser.go
- data/expression/script/gocc/parser/productionstable.go
```
[] Bugfix
[*] Feature
```
**Fixes**: # Supporting nested ternary expression
No nested ternary expression support
Support nested ternary expression as well as add several test cases
> Nested ternary expr

- data/schema/schema.go
- engine/appconfig.go
- engine/config.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Adds the ability to disable built-in schema validation even though schema support is enabled
> separate schema validation and support enabling

- api/support.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
> fix api action settings

- data/mapper/expr.go
- data/mapper/object.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Use ObjectMapping object to specify object mappings   `{ "mapping": ... }`
> use a MappingObject for object mapping

- activity/registry.go
- app/app.go
- app/instances.go
- app/resource/manager.go
- support/cleanup.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
> add activity/resource cleanup support

- activity/legacy.go
- activity/registry.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Add legacy tracking to assist in backwards compatibility issues
> add legacy activity tracking

- data/expression/script/gocc/ast/comparison.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Having issue handle json.Number in the condition expression
Done code to handle json.Number
> Handle json.Number in condition expression

- activity/legacy.go
- activity/registry.go
- trigger/handler.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Add special context for legacy activities that access outputs
> Add legacy activity ctx; improve handler name

- data/path/path.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
Having issue handle type of map.  such as: `type Message map[string]interface`
Handle map as well.
> Handle map type of reflect.

- examples/engine/flogo.json
Fixing log input fields to match the log activity.
```
[x] Bugfix
[] Feature
```
**Fixes**: # NA
When using the CLI to create an app, the generated app includes log activity properties that do not exist on the activity itself.
The generated app should only include valid properties for the activity.
> Update to flogo.json for the generated all in the CLI

- data/expression/script/expr_test.go
- data/expression/script/gocc/ast/literal.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
Today the `\n`, `\t` and `\r` will be treated as a string rather than newline tag...
Make sure convert them to single char to make sure they are acting as `newline` `tab` etc..
> handle \r \t and \n to take real action

- activity/legacy.go
- data/expression/script/gocc/ast/logical.go
- go.mod
- go.sum
- trigger/handler.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
>  remove fmt.println; issue warn on no condition matching action in handler

- data/expression/script/expr_test.go
- data/mapper/config.go
- data/mapper/config_test.go
- data/mapper/expr.go
- data/path/path.go
- data/path/path_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #99 
There is no way to skip failed expression
1. While ENV VAR set to RELAXED then skip the failure expression and just print a warning msg
2. Add single quotes support for map key.
> Skip the expression failure

- data/mapper/object.go
- data/mapper/object_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Having an issue to handle `foreach` source mapping which comes from an activity output and the data a struct
Fix the issue to handle struct for array mapping.
> Having issue handle struct object for array mapping

- data/mapper/object.go
- data/mapper/object_test.go
```
[] Bugfix
[*] Feature
```
**Fixes**: #106 
This is no way to do array mapping base on a filter.
Please check details on #106
> support filtering on array mapper

- data/mapper/object.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Adding index name to original data which invoke a lot issue that original data been changed.
We should come up with a new map and avoid to modify original data.
> Avoid to modify original data

- api/api.go
- api/support.go
- data/types.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Application properties and actions not being initialized with a map, actions not being copied into the application, and action id not being saved. Also adds a Name function to Type.
Setting Flogo API properties and actions is broken.
Flogo API properties and actions work.
> misc fixes needed for async api work

- app/app.go
- data/coerce/connection.go
- support/connection/config.go
- support/connection/manager.go
```
[] Bugfix
[] Feature
[x] Code style update (formatting, local variables)
```
**Fixes**: #
> connections: handle object config; simplify creation

- support/connection/manager.go
```
[] Bugfix
[] Feature
[x] Code style update (formatting, local variables)
```
**Fixes**: #
> add connection release

- data/property/resolver.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
https://github.com/project-flogo/core/issues/121
> Preserving datatype of overridden app property value

- app/resolve/resolve.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
When app property is configured in connection settings, below error is reported by engine:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x136565c]
goroutine 1 [running]:
github.com/project-flogo/core/app/resolve.Resolve(...)
/Users/vnalawad/sourcecode/flogo/workspace/src/github.com/project-flogo/core/app/resolve/resolve.go:16
github.com/project-flogo/core/support/connection.ResolveConfig(0xc000379a80, 0xc0003756e0, …
```
> Fixed nil reference issue

- app/app.go
- support/connection/config.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Alias not supported for ref in connection configuration
Added support for alias resolution for connection type
> Support for alias in connection ref

- support/trace/context.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
> add ability to append/extract tracing context

- trigger/handler.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently, handler schemas are not accessible through API
Added API to access handler output and reply schemas.
> Added API to access handler schemas

- app/app.go
- engine/engineimpl.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Emitting event on app starting
> Emitting App starting event

- activity/context.go
- engine/engineimpl.go
- support/trace/context.go
- support/trace/defaulttracer.go
- support/trace/registry.go
- support/trace/tracer.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Added APIs to enable tracing of actions in core runtime
> Abstracted tracing APIs

- support/connection/config.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
We never init settings to cause settings nil, and NPE when using it..
> init settings for connection to avoid NPE

- data/mapper/object.go
- engine/engine.go
- engine/engineimpl.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
If tracer is not enabled, engine fail to start. This is due to missed trace enabled check during registration of tracer as managed service with the engine.
Added appropriate checks
> Tracing nil error fix

- app/app.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Array mapping does not work on the trigger to flow input mapping
> Add loop resolver as part of app resolver for array mapping

- engine/config_test.go
```
[x] Bugfix
[] Feature
```
**Fixes**:  Small fix to test 
> update enging config test

- api/support.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
FIx compile issue of API package
> FIx compile issue for api package where it missing tracking method

- api/support.go
- data/resolve/composite.go
- data/resolve/resolve.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Handle resolvers that might not have a path like "$error"
> Resolver fix

- data/resolve/loop.go
```
[*] Bugfix
[] Feature
```
**Fixes**: # 
Fixed the $loop has issue handle ` $loop[scopeName]["-abc"]`
> Fix $loop with special char fields. such as: $loop[scopeName]["-abc"]

- docs/mapping.md
```
[] Bugfix
[] Feature
```
Create Mapping Documentation
> Mapping doc

- data/coerce/primatives.go
- docs/mapping.md
```
[x] Bugfix
[] Feature
```
**Fixes**: #116
> Fix for Issue 116

- app/app.go
- support/connection/config.go
- support/connection/manager.go
- support/connection/registry.go
```
[x] Bugfix
[] Feature
```
**Fixes**: Fixes connection settings resolution for inline connection configuration.  Also, fix duplicate detection for connection manager factory.  Add replace method for backwards compatibility feature wise.
> fix connection settings and factory registration

- data/types.go
- support/connection/registry.go
```
[x] Bugfix
[] Feature
```
**Fixes**: Fix connection type resolution, fix connection factory registration logging
> fix type from GoRep; fix connection type log

- data/coerce/coercion_test.go
- data/coerce/primatives.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #174 
coerce.toString not able to convert string pointer to string
Added string pointer to string
> Convert *string to string.

- support/connection/config_test.go
- support/connection/manager_test.go
- support/connection/registry_test.go
- support/managed/managed.go
- support/managed/managed_test.go
```
[x] Bugfix
[] Feature
```
**Fixes**: Panic not converted to error in managed Start/Stop
Also adding unit test for managed and connection packages.
> add connection & managed unit tests; fix panic handling

- support/alias_test.go
- support/compression_test.go
- support/fastuuid_test.go
- support/iterator_test.go
- support/queue_test.go
- support/ref_test.go
- support/service/factory_test.go
- support/service/manager_test.go
- support/trace/context.go
- support/trace/context_test.go
- support/trace/registry.go
- support/trace/registry_test.go
- support/utils.go
- support/utils_test.go
```
[] Bugfix
[] Feature
```
Add unit tests to support package
> add support tests

- data/coerce/coercion_test.go
- data/coerce/compound.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
No way to convert ints to array in coerce to array.
> allow_any_int_in_coerce_array

- app/app.go
- engine/engineimpl.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently no stopping event published while app is stopping.
Publishing **Stopping** event on the event bus for listeners.
> Publishing 'Stopping' event for app

- support/connection/config.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Not able to run legacy flogo.json with connection field
Handle legacy connection to make sure we are able to handle old model as well
> add connection backward compatible

- support/connection/config.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
> Lost return for missing stage

- app/instances.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Schema reference in handler out/reply schema is not resolved.
```
"handlers": [
{
"description": "",
"settings": {
"topic": "toggle",
"topicPattern": "",
"consumerGroup": "asd",
"valueType": "Avro",
"subjects": "String",
"versions": 1,
"commitInterval": 5000,
"initialOffset": "Oldest",
"fetchMinBytes": 1,
"fetchMaxWait": 500,
"heartbeatInterval": 3000,
"sessionTimeout": 30000
},
"action": {
"ref": "github.com/project-flogo/flow",
"settings": {
"flowURI": "res://flow:f2"
},
"input": {
.....
}
},
"schemas": { …
```
> Resolving schema refs in handler schema

- examples/engine/shim/shim_support.go
```
[x] Bugfix
[] Feature
```
**Fixes**: prevent premature garbage collection of engine
> fix shim engine reference

- docs/api.md
```
[] Bugfix
[] Feature
```
Add API Docs
**Fixes**: #
> Add API Doc.

- app/instances.go
```
[] Bugfix
[] Feature
[x] Refactoring (no functional changes, no api changes)
```
**Fixes**: #
Optimized to do resolution only when ref is found.
> Code optimization to call resolution only when ref is found

- app/propertyresolver/env.go
- app/propertyresolver/json.go
- data/property/external.go
- docs/properties.md
- engine/envconfig.go
```
[x] Bugfix
[] Feature
```
**Fixes**: 
Fix code to remove extra hop to deprecated method. Update property documentation.
> Property cleanup

- app/app.go
```
[] Bugfix
[x] Feature
```
Add ability to lifecycle actions is they implement the managed.Managed interface
> add support for ability to lifecycle shared actions

- app/resource/manager.go
```
[] Bugfix
[] Feature
[*] Other... Please describe:
```
**Fixes**: #205 
Not able to set the resource to resource manager after engine initialized
Expose SetResource in resource manager which we can set the additional resource to resource manager
> Provide a method to set resource in manger

- app/app.go
- app/instances.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #211 
The error message is not clear to identify the issue when creating or starting triggers, especially when there multiple triggers in-app.
Make the error message more readable for the user to identify the issue.
> enhance error message when create and start a trigger

- data/expression/script/gocc/ast/builtin.go
…
```
[] Bugfix
[] Feature
[*] Other... Please describe: Enhance function
```
**Fixes**: #
Today `isdefined` function not able to handle when activity output miss or not been set. or any property/env not set.
Enhance isdefined to make sure it able to handle most of not found error thrown by the resolver
> Enhance isdefined function 

- activity/registry.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: Enhancement
```
**Fixes**: #
There is no way to get all registered activity.
`activity.Activities()` will return all registered activities
> Expose an api get all registered activity

- app/app.go
- app/config.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
> add support for special app lifecycle aware triggers

- app/app.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: Enhance code
```
**Fixes**: #
The changes are very simple.  just added below
```
if len(a.triggers) > 0 {
//starting triggeres
//Stoping triggers
}
```
Today, no matter engine have triggers or not engine print below logs
```
2020-10-07T20:20:52.098Z INFO [flogo] - Starting Triggers...
2020-10-07T20:20:52.098Z INFO [flogo] - Triggers Started
```
It is fine with a normal engine as it should have at least one trigger but for a tester engine that just has an empty engine that does not have triggers,  and tester engine only for …
> Print start/stop trigger logs when only engine have triggers

- data/mapper/object.go
- data/mapper/object_test.go
```
[] Bugfix
[*] Feature
```
**Fixes**: #230 
> support index variable in array mapper

- data/mapper/object.go
- data/mapper/object_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #234 
Please  refer to #234 
> support functions for source array and filter expresion in foreach mapping

- support/trace/tracer.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Users cannot use Flogo Xray Tracing as Carrier Format Lambda is not present
Users can now use Flogo Xray Tracing
> added Lambda as a carrier format for xray tracing

- data/metadata/util.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Having issue to backward compatible with old connection model at settings level for trigger or activity
Handle legacy connection for settings which we just handled for activity input previous
> handle connection legacy at settings

- data/path/path.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Passing []bytes to the mapper and it does not work
Fix it.
> Fix []byte not working in mapping

- trigger/context.go
- trigger/handler.go
```
[] Bugfix
[*] Feature
```
**Fixes**: #
Both on PR #254 to simplify the API interface when creating context from event id.
> Simplify API when create context from event id

- trigger/handler.go
```
[] Bugfix
[] Feature
[*] Other... Please describe:
```
**Fixes**: #
> reword log message

- trigger/handler.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
> Moved handler execution time log to debug level

- data/mapper/conditional.go
- data/mapper/conditional_test.go
- data/mapper/expr.go
- data/mapper/object.go
…om flow
```
[] Bugfix
[] Feature
```
**Fixes**: #
Make IsConditionalMapping public to make sure flow init able to call it to determine if mapping is conditional mapping
> Make IsConditionalMapping to public

- app/app.go
```
[] Bugfix
[X] Feature
```
**Fixes**: #
In the test mode we will engine will not be in fail-fast mode but will continue to run even if there are connection error. If the connection is used in any activity and the activity is not mocked then, the unit tests will handle that error.
Engine fails to start if any connection throws error.
Engine will continue to run even if there is connection error.
> Handle connection error case for mocking support

- support/log/logger.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Today there is no way to create a root logger, which prevents us from bypassing the engine log level to log at different log level than engine.
With these changes user will be able to use the `NewLogger(name string)` method to create their own logger with their own log level (different from engine log level)
> add a way to create a new root logger

- data/mapper/config/config.go
- data/mapper/object.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
> Filter nulls for runtime mapping, FLOGO-9292

- data/mapper/object.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
> Fixed FLOGO-11590, omiting nulls from array using foreach

- data/mapper/object.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
> Filter the nulls when dataype is array of interface

- app/app.go
- app/config.go
- data/property/config.go
- data/property/resolver.go
```
[] Bugfix
[X] Feature
```
**Fixes**: #
simple assignment of app properties is resolved at the start of app and remained unchanged.
simple assignment of app properties will be resolved every time we reconfigure  when FLOGO_APP_PROP_RECONFIGURE is set to true
> App reconfigure

- app/app.go
- app/config.go
- data/property/config.go
- data/property/external.go
- data/property/manager.go
- data/property/resolver.go
- engine/envconfig.go
```
[] Bugfix
[X] Feature
```
**Fixes**: #
> added feature dynamic app property reconfigure feature
