project-flogo/core

- data/path/path.go
- data/path/path_test.go
- data/resolve/env_test.go
Makes path handling more consistent. It is not an error if the last path element of a path is not found. Also adds support for multi level paths for values which contain struct values.
> Issue path

- trigger/handler.go
Action doesn't always have IOMetadata: in the case of an action created with a closure through the API there isn't any IOMetadata.
> Skip coerce when IOMetadata is nil

- app/app.go
By setting the app property manager as the default property manager, it solves the issue of properties not being evaluated in expression such as ```=$property[my_property]``` in *flogo.json*.
AFAIK, this fix concerns external resolution as well as classic resolution (from *flogo.json*) as well.
> Set the app property manager as the default property manager

- examples/engine/flogo.json
The expressions in the default *flogo.json* template (used by ```flogo create``` command of the [Flogo CLI](https://github.com/project-flogo/cli)) are missing the leading *=* sign.
As a result expressions are not evaluated, for instance with default application created by the Flogo CLI:
```
547043892330439187	INFO	[flogo.engine] -	Starting app [ test-app ] with version [ 0.0.1 ]
1547043892330464572	INFO	[flogo.engine] -	Engine Starting...
1547043892330471263	INFO	[flogo.engine] -	Starting Services...
1547043892330499314	INFO	[flogo.engine] -	Started Services
1547043892330508566	INFO	[flogo.engine] -	Starting Application...
1547043892330518960	INFO	[flogo] -	Starting Triggers...
1547043892330609569	INFO	[flogo] -	Trigger [ my_rest_trigger ]: Started
1547043892330617442	INFO	[flogo] - …
```
> Fix expressions syntax in default flogo.json

- app/propertyresolver/json.go
Properties loaded from JSON files need to be stored in the ```preload``` map.
> Fix JSON property resolver

- app/app.go
- data/property/manager.go
- data/property/resolver.go
- engine/engineimpl.go
The properties post-processing was mixing inline implementation and clean implementation in typed functions.
There was also a bug where the post processings were called twice.
1. https://github.com/project-flogo/core/compare/master...square-it:property-post-processing?expand=1#diff-886cebc00c073731af1b3da26f11e536L37 : the execution of the options were triggered twice : I deleted the first one.
2. https://github.com/project-flogo/core/compare/master...square-it:property-post-processing?expand=1#diff-ae5650532ac696c0d459a933c48df0a8R76 : external property post processor was moved to the *property* package.
3. https://github.com/project-flogo/core/compare/master...square-it:property-post-processing?expand=1#diff-a6a58e1ba1bcac0ce49fa12af14faaf1R32 : *manager.Finalize* method does not take …
> Simplify properties post-processing implementation

- app/app.go
This is a fix for https://github.com/project-flogo/core/pull/13.
In fact the properties pre-processing need to be done before initializing resources (such as activities).
There were two occurrences of 
```
for _, option := range options {
option(app)
}
```
but I unfortunately removed the wrong one.
> Fix property pre-processing order

- examples/engine/flogo.json
According to https://github.com/project-flogo/cli/blob/99f31dabada136e9cddc2e5202d97011a7a315bc/util/flogo.go#L103, once an import exists in the *imports* array of a *flogo.json* app descriptor, the legacy imports are not loaded by ```flogo list``` command.
By adding them explicitly we ensure they will be displayed by this command.
Accordingly, the ```flogo install``` command should be changed to add new installed contribution to the *imports* list.
It raises also some questions about how to keep in sync app descriptor and Go code.
> Add new format of imports in flogo.json template file

- support/test/context.go
Fix nil pointer error caused by `nil` in activity.Eval() during test
> Fix test Logger

- engine/channels/channels.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Allows multiple integration tests (in the same test file) in microgateway.
channels map is not set to an empty map on stop
channels map is set to a new empty map on stop
> Set channels global map to empty map on stop

- engine/event/emitter.go
```
[x] Bugfix
[] Feature
```
At the end of an event publishing, unlocking the mutex twice (once at the end of the function, another time in the defer) results in a panic.
Publishing an event is working.
> Fix event publishing

- app/app.go
- examples/alt/engine/flogo.json
- examples/engine/flogo.json
```
[] Bugfix
[x] Feature
```
> This PR **is required** to be merged before https://github.com/project-flogo/cli/pull/32
Currently imports in the "imports" array of *flogo.json* file follow the Go import path syntax (including aliases).
Hence it is not possible to know what is the path to the underlying module (if it exists) neither to specify a custom version.
This complicates the interaction of the Flogo CLI with ```go mod``` commands for instance in the ```flogo create``` command and it prevents the *flogo.json* to recreate an application in a …
> Support classic and alternate import syntax in flogo.json

- data/mapper/deprecated.go
- data/mapper/deprecated_test.go
- trigger/config.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: support legacy mapping
```
**Fixes**: 
As we changed the way of handling object mapping.  previous we used multiple mapping to a single field value now we are coming up with object mapper which handle `object` + `array mapping`
The PR use to handle old mapper,  to convert old mapping format to new. such as:
1. Convert multiple mapping to single object mapping
```
"input": [
{
"mapTo": "input1.a.b",
"type": "expression",
"value": "$.body.id"
},
{
"mapTo": "input1.a.c",
"type": "expression",
"value": …
```
> Objectmapper compatibility

- app/config.go
```
[x] Bugfix
[] Feature
```
Some content from commit https://github.com/project-flogo/core/pull/20/commits/261af9b in PR #20 was lost after a rebase.
Some optional keys are saved with a null value in *flogo.json* file:
```
"properties": null,
"channels": null,
"actions": null
```
If the key is optional and not present, it is not saved in *flogo.json*
> Restore lost content from PR #20

- app/propertyresolver/env.go
- app/propertyresolver/json.go
- data/property/resolver.go
- engine/config.go
- engine/engineimpl.go
```
[] Bugfix
[x] Feature
```
**Related to**: #9 
Property resolvers are enabled:
1. by importing their package which will register the resolver at engine startup.
2. by setting ```FLOGO_APP_PROP_RESOLVERS``` environment variable with a comma-separated list of resolvers names (for instance ```FLOGO_APP_PROP_RESOLVERS=env,json```)
It exists two "builtin" resolvers (provided by github.com/project-flogo/core) called "env" & "json" and any number of "custom" resolvers can be registered from other contributions.
**Setting an environment variable to enable …
> Initialization of property resolvers

- data/mapper/object.go
- data/mapper/object_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Have issue handle 
```
{
"features": [
{
"name": "inputs",
"data": [
"=$.result.V1",
"=$.result.V2",
"=$.result.V3",
"=$.result.V4"
]
}
]
}
```
FIx it by adding it as an test cases
> Object mapper issue with primitive array

- data/mapper/expr_test.go
- data/mapper/object.go
- data/mapper/object_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
There have some mix-up issues while no foreach(arraymapping) at the second level 
> Fix object mapping when second level no foreach

- data/resolve/resolve.go
- data/resolve/resolve_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
IsResolveExpr returns true for expression which does not have space such as `$activity[acb].id==1`
IsResolveExpr should return false for condition expression, ternary expression and indexer Expr
> IsResolveExpr should return false for expressions

- data/mapper/object_test.go
- data/resolve/composite.go
- data/resolve/loop.go
- data/resolve/resolve.go
- data/resolve/resolve_test.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: Change the way of access current loop element
```
**Fixes**: #79 
Please have a look #79.  Today we are using `$.` to access current scope data which also use to access array mapping current loop.
With this PR, we changed to `$loop.xxx` to access the current loop.
@fm-tibco I added one more field call IsImplicit in ResoverInfo which indicate the resolver intent to support both(has item or no item).
As the loop to be supported.
`$loop.xxx`  to access the current loop element
`$loop[name].xxx` to …
> Access current loop use $loop

- data/path/path.go
- data/path/path_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
The connector defined a struct with json tag.  they use json tag name as mapping ref to access the value but it cannot today
Fix it by getting value from object field name or json tag name.
1. Try to get value from the field name.
2.  Try to json tag if first 1 invalid.
> Get object value base on field name and json tag name

- data/mapper/object.go
- data/mapper/object_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
If there is no child mapping for array mapping then we return original data. such as:
```
"array": {
"@foreach($activity[rest].data.array)":{}
}
```
We will copy `$activity[rest].data.array` to `array`.  This is the behavior we did in flogo-lib,  so make these changes to keep consistency with previous.
> return original array if no child mapping for array mapping

- data/coerce/coercion_test.go
- data/coerce/compound.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Not able to convert a struct to an object when a user tries to set struct value as trigger data. 
The handler cannot convert struct to an object base on metadata.
Able to convert struct to an object.
> Convert struct to object

- data/expression/util.go
- data/expression/util_test.go
… quotes
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Expression `"flogo" == "flogo"` be treated at literal rather than expression.
The quotes string must be surrounded with quotes and only have one pair of quotes
> Fixing check literal 

- data/expression/script/expr_test.go
- data/expression/script/gocc/ast/literal.go
- data/mapper/object_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Today we have issue handle escaped quotes in expr.  such as `string.concat("\"Hello\" ", '\'FLOGO\'')`
Expected result: `"Hello" 'FLOGO'`
Handle in expression to get correct escaped value
> Handle escaped double quotes and single quotes

- data/expression/script/expr_test.go
- data/expression/script/gocc/ast/builtin.go
- data/expression/script/gocc/ast/function.go
```
[] Bugfix
[*] Feature
```
**Fixes**: #
1. There is no function to check the mapping node exist or not
2. No function to set a default value while mapping node doesn't exist
1. Added builtin function `isDefined($.xxxxx)`
2. Added builtin function `getValue($.xxxxx, "defaultValue")`
> Add builtin function isDefined and getValue

- support/ssl/client.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Seems like this code is duplicated everywhere and done differently everywhere.  I propose we add this package which people can use in their contribs that use TLS.  In addition to sharing the same code, we can also have contribs just use a single field in their settings for TLS.  Which is really nice for configuration is someone isn't using it.
So instead of: 
```
"settings": [
{
"name": "method",
"type": "string",
"required": true,
"allowed": [ "GET", "POST", "PUT", "PATCH", "DELETE" …
```
> Shared SSL Config

- README.md
Fix flogo cli link address to https://github.com/project-flogo/cli, originally it's a url to `flogo/core`.
```
[] Bugfix
[] Feature
```
**Fixes**: # Readme link error
**What is the current behavior?** link to `flogo/core`
**What is the new behavior?** link to `flogo/cli`
> Fix flogo cli link address

- data/mapper/object.go
- data/mapper/object_test.go
- data/path/path.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Cannot handle when a struct has json tag which has `omitempty` or `-`
FIxed the issue to get only the field tag name rather than `omitempty` or `-`
> handle json tag with omitempty

- activity/legacy.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
There is no way to get legacy activity setting fields.
Add GetSetting method in legacycxt
> Add GetSetting method to handle legacy activity

- data/mapper/object.go
- data/mapper/object_test.go
- data/resolve/loop.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
We just add array element data into current data scope when means we still can use $.xxx to get it.
We should only allow using $loop.xxx to access array mapping data otherwise it will have an issue when use array mapping in the trigger to flow or flow to trigger mapping
> Fix an issue regarding array mapping accessing scope

- app/app.go
- app/config.go
- data/coerce/coercion.go
- data/coerce/connection.go
- data/types.go
- support/connection/config.go
- support/connection/manager.go
- support/connection/registry.go
- support/ssl/client.go
```
[] Bugfix
[x] Feature
```
This code allows shared connections to be configured in the app.  It assumes the following section is added to the flogo.json
```json
"connections": {
"myrestConn": {
"type": "http",
"settings": {"":""}
}
}
```
An activity that uses connection, just needs to expose a setting that indicates the id of the connection. And if this is set, it can use the connection.GetManager() to get the shared manager for it to use.  If an id isn't specified, it can create its own "local" manager to keep the client connection code consistent.
> initial shared connection support

- activity/error.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently, activity contributions could only throw one type of activity error.
Added a new constructor `NewRetriableError` that allows contributions to return a retriable error if the error could possibly be fixed on retry. For this task needs to be configured with `retryonerror`. More information about `retryonerror` is available at https://github.com/project-flogo/flow/pull/35
This feature is needed for the above PR to work.
> Added new retriable error to activity help PR #35 in project-flogo/flow

- app/app.go
- engine/engineimpl.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Today listeners can not gather application events like started, failed or stopped. In certain scenarios, listener may want to initialize certain things based on application status. e.g. Datadog event listener wants to enable application tracer only after app is successfully started
Added new event type **_appevent_** that listeners can subscriber to get application lifecycle events like Started, Stopped and Failed.
> Emmitting application lifecycle events to listeners

- support/trace/registry.go
```
[] Bugfix
[] Feature
[x] Code style update (formatting, local variables)
```
**Fixes**: #
There are Info statements from `Register()` that get printed before engine starts as the implementations register the tracer at `init()`.
Changed level to debug and move any implementation logs to `managed.Start()`
> change to debug to avoid adding print statements before engine starting

- data/path/path.go
- data/path/path_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Today, we have an issue to get value from struct where it has map key such as `$activity[xxxx].output.object["T!T"]`
> Get value from struct while mapping ref has map key.

- app/app.go
- app/instances.go
- trigger/config.go
- trigger/event.go
- trigger/handler.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Today, trigger related lifecycle events like start/stop/errors, total number of jobs started/faulted/completed (across all handlers) or handler related events like number of jobs started/faulted/completed are not published by the engine. 
With this change, now event listeners can collect events related to trigger and handler.
> Publishing Trigger and handler events 

- data/mapper/object.go
- data/mapper/object_test.go
- trigger/handler.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: Object mapper optimization because of performance issue.
```
**Fixes**: #
Today we parse expression inside object mapper when running object mapper at runtime which causes performance bad
Now we do parse expression inside expression at engine startup and runtime just execute it(Eval)
See benchmark improve.
```
Before
BenchmarkObj-12  100000	  17260 ns/op	   11648 B/op	  136 allocs/op
After:
BenchmarkObj-12   300000  3682 ns/op	    2472 B/op	   32 allocs/op
```
We can see which improve much better.
> Object mapper optimize

- trigger/event.go
- trigger/handler.go
```
[] Bugfix
[x] Feature
```
The following can be used to attach event data to a context.  This would be used when creating the context that is passed when a handler is invoked.  That data will added to the handler's events.
```
NewContextWithEventData(parentCtx context.Context, data map[string]string) 
```
The `HandlerEventConfig` interface is implemented by handlerImpl.  It can be used when processing handlers in a trigger's `Initialize` to set the default event data to attach to the handler's events.
> add support for setting event data from handler

- data/coerce/connection.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #https://github.com/project-flogo/flow/issues/112
Return panic error if connection value is empty
1. Avoid panic and just return nil if connection value is empty to let connector dev to handle the empty cases. 
Refer to issue https://github.com/project-flogo/flow/issues/112
> Return connection to nil if connection value empty

- data/mapper/object.go
- data/mapper/object_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #199 
Assume the source data is books and books have more than one author. authors are a string array. Now we want to assign this string array to another string array using below mapping
```
{
"mapping": {
"books": {
"authors": {
"@foreach($.books[0].authors, index)": {
"=": "$loop"
}
}
}
}
}
```
Today it will fail say cannot convert string to map.
Fixed it and it able to handle now.
> new loop scope only when there is filter for assign all case.

- engine/envconfig.go
- engine/event/env.go
- engine/event/events.go
- engine/event/publish.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #209
Today we hardcode event queue size to 100 which is not good. For high loading requests, the 100 queues might be the bottleneck.
We should able to configure the value from env vars.
> configure event queue size from env var

- data/mapper/object.go
- data/mapper/object_test.go
```
[] Bugfix
[] Feature
```
**Fixes**: #213 
Using below mapping which returns null rather than []
```
{
"field": {
"mapping": {
"array": []
}
}
}
```
Now returns
```
{
"field": {
"array": null
}
}
```
returns
```
{
"field": {
"array": []
}
}
```
> Fix issue #213 to handle empty array

- app/instances.go
- data/expression/script/gocc/ast/function.go
```
[] Bugfix
[] Feature
[*] Refactoring (no functional changes, no api changes)
```
**Fixes**: #
Error message for trigger not import, today
```
Failed to create engine: trigger [timer]'s 'ref' [#timer] not imported
```
Today's error message which not very clear for user to know what happens. 
Change to below 
```
Failed to create engine: incompatible app engine, the app using the trigger [timer] with ref [#timer] is not installed
```
> Improve error message when function or trigger not import in engine

- data/expression/script/expr_test.go
- data/expression/script/gocc/ast/arithmetic.go
- data/expression/script/gocc/ast/comparison.go
- data/expression/script/gocc/ast/unary.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
The engine has an issue to deal with an expression that has json.number, such as a contribution which return as json.number as output field1
$activity[xxxxx].field1 * 32
$activity[xxxxx].field1 / 32
We will have issue because we never take json.Number as the number at the engine
Fixed above an issue that json.Number can be used in the expression.
> Handle json.Number type in expression

- data/coerce/compound.go
- trigger/handler.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: Code optimize
```
**Fixes**: #
1. Today we unmarshal Go Object from either string to an interface which requires conversion if it is an array of byte
2. Additional scope created which has been created.
1. Unmarshal Go object from the byte array
2. Avoiding to create a duplicate scope.
> Unmarshalling Go object from byte array

- app/app.go
- app/config.go
- app/controller.go
- trigger/trigger.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
https://github.com/project-flogo/core/issues/226
Today, engine will simply accept as many events as possible(Direct Runner) or block trigger go-routines when worker queue is full(Pooled Runner). This could lead to a performance issue or even loss of events due to resource constrains like CPU and Memory or blocked workers(Pooled runner). This might also lead to engine crash. 
Added new interface that Trigger implementations can implement to support pause/resume.  Also added a …
> Engine flow control support

- app/app.go
- support/alias.go
- support/connection/config.go
```
[] Bugfix
[] Feature
```
**Fixes**: #231 
Now it throws below error message when the connection not been imported to the engine
```
connection ' ' not imported
```
We should throw a meaningfully error message. such as:
```
connection 'PulsarConn' with ref 'github.com/project-flogo/messaging-contrib/pulsar/connection' not imported
```
> Fix #231 to report clearly error message when connection not imported

- app/data.go
- data/scope.go
```
[] Bugfix
[*] Feature
```
**Fixes**: #237 
Today we exposed api app.GetValue and app.SetValue() to save app-level data, and we already had a appdata activity https://github.com/project-flogo/contrib/blob/master/activity/appdata/activity.go .
But there is no way to delete an attribute from the app data cache. It's better to have the ability to delete data as a global data store.
Ability to remove/delete app data.
> Fix #237 to delete data from app data

- app/app.go
- app/controller.go
- app/controller_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Today we are using single blocked channel to control the controller which somehow difficult to control if there is more than one evaluator try to control the app. 
Now I removed the single blocked channel to use the explicit **StartControl** and **ReleaseControl** interface. 
Any evaluator must call StartControl first then Release Control.   Error throw back if the App already been controlled.
> App controller interface optimizing

- activity/legacy.go
- activity/registry.go
- app/instances.go
- support/log/logger.go
- support/test/trigger.go
- trigger/deprecated.go
- trigger/handler.go
- trigger/handler_test.go
- trigger/registry.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
The PR has 2 fixes
1. Changer logger name to have the category name.  such as `flogo.contrib.activity.log` `flogo.pulsar.activity. publish`, same for trigger
2.  Create a child handler logger from the trigger.  1 trigger has multiple handlers so it makes sense to have the handler's own logger.
1.  Today we just take `flogo.activity.ActivityTypeName` as logger name which will have an issue if one flow has many query activity which comes from different contribution which will have difficult to know which `query` …
> logger enhancement

- trigger/context.go
- trigger/handler.go
```
[] Bugfix
[] Feature
[X] Refactoring (no functional changes, no api changes)
```
**Fixes**: #224 
> merge change for issue #224

- app/instances.go
- trigger/handler.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: Enhance the handler logger
```
**Fixes**: #
Today we added handler name as part of logger name which causes trigger name too long if user have a long name for the handler. 
Move handler name to context logger which only prints when enabling context logging.
> Add handler name and trigger id as context of handler logger

- data/coerce/compound.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
When trying to convert []bytes to an array using Totype which just returns []byte but we expected to return go object array.
Convert byte array to Go object array.
> We should handle []byte to array rather just return byte array

- support/log/logger.go
- support/log/zap.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #251 
Today we print error stack trace at INFO or ERROR LEVEL which prints too many logs.  The stack trace should be print when only for Log Level at DEBUG or wider level.
```
021-03-25T10:01:46.491-0500    DEBUG   [flogo.contrib.activity.error] -        Applying InputMapper
2021-03-25T10:01:46.491-0500    DEBUG   [flogo.contrib.activity.error] -        Message :'dadsasdasdasdasd', Data: '<nil>'
2021-03-25T10:01:46.492-0500    INFO    [flogo.contrib.activity.error] -        Eval activity [ThrowError] on instance …
```
> Print error stack trance only on debug mode

- trigger/context.go
- trigger/handler.go
```
[] Bugfix
[*] Feature
```
**Fixes**: #252 
* Today there is no way that we can track requests from triggers always down to action instances in logs.  such as Trigger -> Handler -> Action -> Done.  It is super difficult to debugging from logs or find a way that can associate one request from handler to flow instance.  
* No handler execution time took been printed at logs
* I came up with a way that each request from the hander will associate with a unique key(Event Id with UUID), the key will be pass to action instance …
> Give unique id(eventid) for each handler request to tight with action instance

- data/mapper/object.go
- data/mapper/object_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
When do array mapping with assign, such as mapping 
```
"@foreach($.books, index, $loop.title == \"IOS\")":{
"=":"$loop"
}
```
With source array 
```
{
"title": "IOS",
"isbn": "1935182722",
"pageCount": 592,
"publishedDate": { "$date": "2011-01-14T00:00:00.000-0800" },
"status": "PUBLISH",
"authors": ["W. Frank Ableson", "Robi Sen"],
"categories": ["Java"]
}
```
extra `index` array elements have been added to the result. 
```
{
"index":0,
"title": "IOS",
"isbn": "1935182722",
"pageCount": 592,
"publishedDate": { …
```
> Adding extra index field when do array mapping assign

- app/app.go
- app/controller.go
- app/instances.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
When we have multiple OnStartup Triggers be added in one app. the order of those triggers is not guaranteed.  Sometime it is random because we are using the map to store them in Go, The map in go doesn't maintain order. 
Convert Map to array to make sure the order is matter
> maintain trigger startup order especially for lifecycle triggers

- activity/activity.go
- app/app.go
- app/config.go
- app/controller.go
- app/instances.go
- app/resource/manager.go
- app/resource/resource.go
- support/connection/manager.go
- support/connection/registry.go
- trigger/trigger.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
In some cases, users would like to auto reconfigure app without restarting engine. The updated value could be used in triggers/connections/activities settings. Currently, engine restart is the only way to force trigger/connection/activity settings be reconfigured with new values.
With new features, trigger/connection/activity can act on updated configuration by implementing additional interface. When reconfiguration is triggered through REST API (manually) or configuration management …
> Dynamic reconfiguration support

- activity/activity.go
- api/support.go
- support/test/context.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently activity name is not available in the [InitContext](https://github.com/project-flogo/core/blob/master/activity/activity.go#L21). Due to this, activity name can not be used during initialization. e.g. Pulsar producer name
With this change, contribution developers can access activity name during initialization.
> Activity name in context

- activity/activity.go
- api/support.go
- support/test/context.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently activity host name is not available in the [InitContext](https://github.com/project-flogo/core/blob/master/activity/activity.go#L21). Due to this, activity host name can not be used during initialization. e.g. Pulsar producer name
With this change, contribution developers can access activity host name during initialization.
> add hostname in the initContext

- app/controller.go
```
[X] Bugfix
[] Feature
```
**Fixes**: #
Added logic to print logs for while pausing and resuming functions when flow control is enabled.
Pause and resume logs are printed irrespective if the trigger is flow controlled or not.
Pause and resume will be called when the trigger is flow controlled.
> added logic to print logs for pause and resume triggers

- data/schema/support.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
expose schemaSansValidation schema creation for app level schema cases.
Runtime returns schemaSansValidation pointer for app level schemas.
Developers can use FindOrCreate method to parse app level schema.
> expose schemaSansValidation schema creation.

- data/expression/script/gocc/ast/comparison.go
- data/expression/script/gocc/ast/expr.go
- data/expression/script/gocc/ast/function.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Add missing fields for expressions in Unit test results
Currently the fields are missing in Unit test results
The new fields are added in the Unit test results
> Unit testing phase2
